# Generated by Django 5.0.6 on 2024-05-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(default='photos/default.jpg', upload_to='photos/%Y%m%d/'),
        ),
    ]
