# Generated by Django 5.0.6 on 2024-05-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0006_alter_staff_photo_alter_staff_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
    ]
