# Generated by Django 5.0.6 on 2024-05-29 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_loans_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='apply_status',
            field=models.CharField(choices=[('未审批', '未审批'), ('批准', '批准'), ('拒绝', '拒绝')], default='未审批', max_length=10),
        ),
        migrations.AlterField(
            model_name='loans',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 29, 14, 2, 0, 660688)),
        ),
        migrations.AlterField(
            model_name='loans',
            name='status',
            field=models.CharField(choices=[('未还清', '未还清'), ('已还清', '已还清')], default='未还清', max_length=10),
        ),
    ]
