# Generated by Django 5.0.6 on 2024-05-21 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('property', models.DecimalField(decimal_places=8, max_digits=28)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_relationship', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=8, max_digits=28)),
                ('balance', models.DecimalField(decimal_places=8, default=models.DecimalField(decimal_places=8, max_digits=28), max_digits=28)),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Client_Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server.client')),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server.loan')),
            ],
            options={
                'unique_together': {('client_id', 'loan_id')},
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('is_manager', models.BooleanField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('hiredate', models.DateTimeField(blank=True, null=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server.department')),
            ],
        ),
        migrations.CreateModel(
            name='SavingAccount',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=200)),
                ('balance', models.DecimalField(decimal_places=8, max_digits=28)),
                ('interest_rate', models.DecimalField(decimal_places=8, max_digits=28)),
                ('open_date', models.DateTimeField(blank=True, null=True)),
                ('last_access_date', models.DateTimeField(blank=True, null=True)),
                ('staff_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='server.staff')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='server.staff'),
        ),
        migrations.CreateModel(
            name='CheckingAccount',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=8, max_digits=28)),
                ('overdraft', models.DecimalField(decimal_places=8, max_digits=28)),
                ('open_date', models.DateTimeField(blank=True, null=True)),
                ('last_access_date', models.DateTimeField(blank=True, null=True)),
                ('staff_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='server.staff')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=8, max_digits=28)),
                ('client_loan_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='server.client_loan')),
            ],
            options={
                'unique_together': {('client_loan_id', 'release_date')},
            },
        ),
        migrations.CreateModel(
            name='Client_Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server.branch')),
                ('checking_account_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='server.checkingaccount')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server.client')),
                ('saving_account_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='server.savingaccount')),
            ],
            options={
                'unique_together': {('client_id', 'branch_name')},
            },
        ),
    ]
